### ISSUE TITLE
Exception: Backend Arch.vulkan doesn't support dynamic index (with NVIDIA GPU)

### ISSUE THREAD

**Issue by ezbird** [PolyPhyHub/PolyPhy#34]
Reporting an exception with running "PolyPhy_2D_discrete_data.ipynb" from the experiments folder.

Exception: Backend Arch.vulkan doesn't support dynamic index

**Note ----------**
Switching arch parameter to "ti.cuda" in  ti.init(arch=ti.gpu, dynamic_index=True)   does load PolyPhy successfully, albeit slowly (~7 fps)

**Architecture ----------**
OS: Mint Linux 20.3 Cinnamon
CPU: Intel© Core™ i7-4770 CPU @ 3.40GHz × 4
GPU: NVIDIA Corporation GF119 [GeForce GT 610]

**Full exception output ----------**
TaichiCompilationError: 
File "/home/olive/.local/lib/python3.8/site-packages/taichi/_kernels.py", line 183, in ext_arr_to_matrix:
    for I in grouped(mat):
    ^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/olive/.local/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "/home/olive/.local/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer.py", line 1167, in build_For
    return ASTTransformer.build_struct_for(ctx,
  File "/home/olive/.local/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer.py", line 1063, in build_struct_for
    target, matrix.Vector(loop_indices,
  File "/home/olive/.local/lib/python3.8/site-packages/taichi/lang/matrix.py", line 1481, in __init__
    super().__init__(arr, dt=dt, **kwargs)
  File "/home/olive/.local/lib/python3.8/site-packages/taichi/lang/matrix.py", line 468, in __init__
    raise Exception(
Exception: Backend Arch.vulkan doesn't support dynamic index

**Comment by deehrlic** [comment]
PolyPhy can currently only be used with CUDA GPUs because of this - @OskarElek knows about this and has plans to add compatibility for Vulkan and Metal once a solution presents itself. Sorry I don't have a more helpful answer :(

**Comment by deehrlic** [comment]
Hi @ezbird can you try updating your taichi to 1.5.0 with `pip install taichi==1.5.0` and removing the `dynamic_index=True` from the ti.init call so it just says `ti.init(arch=ti.vulkan)` and let me know how it runs? Taichi has now updated to allow for dynamic indexing on all backends - I can get 2D notebooks running on my RX 5500 XT GPU.

**Comment by deehrlic** [comment]
You might need to also download the Vulkan SDK and runtime from here: https://vulkan.lunarg.com/sdk/home if Taichi throws an error about GGUI and Vulkan not being set up properly.

**Comment by pjflux2001** [comment]
@deehrlic were you able to get this running without gpu / cuda arch? is yes, please share a copy of the `pip list`command, alongwith info about your machine using `uname -a` and `cat /etc/os-release` commands.

**Comment by deehrlic** [comment]
Yes using cpu backend works, just runs at low framerates like what ezbird experienced. output of pip list and systeminfo (im on windows) atttached, I am using a conda env just for this project so it should only have libs from running my notebook.

[piplist.txt](https://github.com/PolyPhyHub/PolyPhy/files/11522926/piplist.txt)
[sysinfo.txt](https://github.com/PolyPhyHub/PolyPhy/files/11522929/sysinfo.txt)

**Comment by deehrlic** [comment]
To my understanding this issue has been resolved. Taichi has removed the dynamic index requirement so Vulkan machines can now run Polyphy with the Vulkan SDK and runtime installed. Even though there are other Vulkan bugs, these are in a different issue.

https://github.com/PolyPhyHub/PolyPhy/issues/46

**Comment by ezbird** [comment]
Just following up here... with Taichi 1.6, I can successfully run "ti.init(arch=ti.gpu, debug=True)" on a linux laptop GPU... Polyphy runs at 22 fps! Nice

**Comment by OskarElek** [comment]
Thanks guys for talking through this! Since this is deprecated I'm going to close is now.
