### ISSUE TITLE
Remove hardcoding from jupyter notebooks

### ISSUE THREAD

**Issue by PatriceJada** [PolyPhyHub/PolyPhy#42]
`ROOT = 'c:/UCSC/Projects/PolyPhy/repo/PolyPhy/'`,  use relative paths. 
Assume that we are starting from the main directory of the repo
https://github.com/PolyPhyHub/PolyPhy/blob/main/experiments/jupyter/PolyPhy_3D_mask_data.ipynb

**Comment by OskarElek** [comment]
Deprecated issue, development moved away from Jupyter notebooks
