### ISSUE TITLE
Add documentation about using jupyter notebooks 

### ISSUE THREAD

**Issue by PatriceJada** [PolyPhyHub/PolyPhy#43]
We can include some notes about how to run the jupyter notebooks for the project in the README file or the docs.
Something like:
` pip install jupyterlab`

How to launch jupyterab:
`jupyter-lab
`

ref: https://jupyter.org/install

**Comment by OskarElek** [comment]
Closing as deprecated, Jupyter notebooks are no longer the main development environment (src/ is)
