### ISSUE TITLE
Screenshot button

### ISSUE THREAD

**Issue by ezbird** [PolyPhyHub/PolyPhy#59]
Polyphy crashes after Screenshot button is clicked on Mint Linux 20.3 Cinnamon with 11th Gen Intel© Core™ i5-1135G7 @ 2.40GHz × 4. Are any other details useful?

**Comment by pjflux2001** [comment]
What does the terminal say once it crashes?

**Comment by OskarElek** [comment]
I think this is fixed. Can anyone confirm?

**Comment by Shahbaz898414** [comment]
@OskarElek 
Can you assign me?

**Comment by Abhinavcode13** [comment]
Go Ahead ! @Shahbaz898414

**Comment by Abhinavcode13** [comment]
This is fixed
