### ISSUE TITLE
Make simulation margin a command line argument

### ISSUE THREAD

**Issue by OskarElek** [PolyPhyHub/PolyPhy#75]
The discrete 2D and 3D pipeline add a margin into the simulation domain (reflected in the trace and deposit solutions).

This margin is a parameter hardcoded in the common.py->PPConfig class as DOMAIN_MARGIN parameter. This should be configurable from the CLI as an argument to polyphy.

**Comment by Abhinavcode13** [comment]
Is the directory is `src/ployphy` -> `Core` -> `common.py` ? @OskarElek

**Comment by OskarElek** [comment]
Yes @Abhinavcode13 that's correct.

In general there's an existing pipeline for parsing cmd arguments and setting them in the specific instance of PPConfig. This is implemented in utils/cli_helper.py so that's a natural place to add the functionality.

Testing can then be done in any of the pipelines, the 2D Discrete one would be the simplest to do so.
