### ISSUE TITLE
Clicking the UI also registers a click in the main rendering context

### ISSUE THREAD

**Issue by OskarElek** [PolyPhyHub/PolyPhy#76]
This is currently the standard behavior in Taichi, clearly should not work like this.

As a workaround, editing in the 2D pipelines can be disabled, until Taichi fixes this.

**Comment by Abhinavcode13** [comment]
Can I you elaborate on this issue more would like to work upon it.
Thanks!

**Comment by OskarElek** [comment]
Sure @Abhinavcode13 

When you open one of the pipelines (e.g. 2D Discrete) in the GUI mode (which is the standard mode) there's a UI panel with controls like sliders and switches. Left-clicking any of these elements will also send a left click event to the main window, which in some pipelines invokes another action.

That's undesired behavior. If the user clicks on a UI element, that element should be the only one that receives the event. This is related to Taichi as the provider of the GUI and generally GPU API. Perhaps Taichi has a way of changing this behavior, or at least a reported issue we could reference.
