### ISSUE TITLE
Overlapping of navbar elements

### ISSUE THREAD

**Issue by psankhe28** [PolyPhyHub/PolyPhy#83]
In the provided image, there is an overlap between "Opportunities" and "Agents" in the navbar section. I would like to address and resolve this issue. Can I proceed with resolving it?

![image](https://github.com/PolyPhyHub/PolyPhy/assets/84843461/6be00ee9-9625-46c0-ab6c-f3f2867ec916)

**Comment by Shahbaz898414** [comment]
can you assign me plz?

**Comment by psankhe28** [comment]
I am waiting for the maintainer's approval and I will work on it. Please find some other issue.

**Comment by Abhinavcode13** [comment]
Please do open website related issues in https://github.com/PolyPhyHub/PolyPhy-Website
Thanks!
